[2025-04-10T03:11:29.288+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-10T03:11:29.340+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: realtime_user_streaming_pipeline.data_validation manual__2025-04-10T03:06:26.209555+00:00 [queued]>
[2025-04-10T03:11:29.344+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: realtime_user_streaming_pipeline.data_validation manual__2025-04-10T03:06:26.209555+00:00 [queued]>
[2025-04-10T03:11:29.344+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 4
[2025-04-10T03:11:29.350+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): data_validation> on 2025-04-10 03:06:26.209555+00:00
[2025-04-10T03:11:29.357+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'realtime_user_streaming_pipeline', 'data_validation', 'manual__2025-04-10T03:06:26.209555+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/realtime_streaming.py', '--cfg-path', '/tmp/tmp5hnxscm2']
[2025-04-10T03:11:29.364+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=361) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-10T03:11:29.364+0000] {standard_task_runner.py:91} INFO - Job 31: Subtask data_validation
[2025-04-10T03:11:29.364+0000] {standard_task_runner.py:64} INFO - Started process 362 to run task
[2025-04-10T03:11:29.418+0000] {task_command.py:426} INFO - Running <TaskInstance: realtime_user_streaming_pipeline.data_validation manual__2025-04-10T03:06:26.209555+00:00 [running]> on host 4b246fcce89d
[2025-04-10T03:11:29.468+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data_engineer' AIRFLOW_CTX_DAG_ID='realtime_user_streaming_pipeline' AIRFLOW_CTX_TASK_ID='data_validation' AIRFLOW_CTX_EXECUTION_DATE='2025-04-10T03:06:26.209555+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-10T03:06:26.209555+00:00'
[2025-04-10T03:11:29.469+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-10T03:11:29.489+0000] {data_validator.py:251} INFO - Data validation completed: 0 valid, 100 invalid records
[2025-04-10T03:11:29.489+0000] {data_validator.py:255} WARNING - Validation failures breakdown: {"required_fields": 0, "email_format": 0, "date_format": 0, "username_unique": 100, "data_types": 0, "value_constraints": 0}
[2025-04-10T03:11:29.490+0000] {etl_pipeline.py:72} INFO - Data validation summary: 0 valid, 100 invalid records
[2025-04-10T03:11:29.500+0000] {etl_pipeline.py:81} WARNING - Validation report: {
  "total_invalid": 100,
  "issues_by_field": {},
  "issues_by_rule": {
    "required_fields": 0,
    "email_format": 0,
    "date_format": 0,
    "username_unique": 100,
    "data_types": 0,
    "value_constraints": 0
  }
}
[2025-04-10T03:11:29.500+0000] {etl_pipeline.py:87} WARNING - Found 100 invalid records that will not be sent to Kafka
[2025-04-10T03:11:29.503+0000] {etl_pipeline.py:91} INFO - Data validation completed. 0 records ready for loading.
[2025-04-10T03:11:29.503+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-04-10T03:11:29.503+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-10T03:11:29.507+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=realtime_user_streaming_pipeline, task_id=data_validation, run_id=manual__2025-04-10T03:06:26.209555+00:00, execution_date=20250410T030626, start_date=20250410T031129, end_date=20250410T031129
[2025-04-10T03:11:29.549+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-04-10T03:11:29.560+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-10T03:11:29.561+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
