[2025-04-10T03:13:26.555+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-10T03:13:26.569+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: realtime_user_streaming_pipeline.data_validation manual__2025-04-10T03:13:23.288254+00:00 [queued]>
[2025-04-10T03:13:26.573+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: realtime_user_streaming_pipeline.data_validation manual__2025-04-10T03:13:23.288254+00:00 [queued]>
[2025-04-10T03:13:26.573+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 4
[2025-04-10T03:13:26.578+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): data_validation> on 2025-04-10 03:13:23.288254+00:00
[2025-04-10T03:13:26.586+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=210) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-10T03:13:26.586+0000] {standard_task_runner.py:64} INFO - Started process 211 to run task
[2025-04-10T03:13:26.582+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'realtime_user_streaming_pipeline', 'data_validation', 'manual__2025-04-10T03:13:23.288254+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/realtime_streaming.py', '--cfg-path', '/tmp/tmp28j7oamd']
[2025-04-10T03:13:26.588+0000] {standard_task_runner.py:91} INFO - Job 36: Subtask data_validation
[2025-04-10T03:13:26.613+0000] {task_command.py:426} INFO - Running <TaskInstance: realtime_user_streaming_pipeline.data_validation manual__2025-04-10T03:13:23.288254+00:00 [running]> on host 4b246fcce89d
[2025-04-10T03:13:26.660+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data_engineer' AIRFLOW_CTX_DAG_ID='realtime_user_streaming_pipeline' AIRFLOW_CTX_TASK_ID='data_validation' AIRFLOW_CTX_EXECUTION_DATE='2025-04-10T03:13:23.288254+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-10T03:13:23.288254+00:00'
[2025-04-10T03:13:26.661+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-10T03:13:26.678+0000] {data_validator.py:251} INFO - Data validation completed: 0 valid, 100 invalid records
[2025-04-10T03:13:26.678+0000] {data_validator.py:255} WARNING - Validation failures breakdown: {"required_fields": 0, "email_format": 0, "date_format": 0, "username_unique": 100, "data_types": 0, "value_constraints": 0}
[2025-04-10T03:13:26.678+0000] {etl_pipeline.py:72} INFO - Data validation summary: 0 valid, 100 invalid records
[2025-04-10T03:13:26.685+0000] {etl_pipeline.py:81} WARNING - Validation report: {
  "total_invalid": 100,
  "issues_by_field": {},
  "issues_by_rule": {
    "required_fields": 0,
    "email_format": 0,
    "date_format": 0,
    "username_unique": 100,
    "data_types": 0,
    "value_constraints": 0
  }
}
[2025-04-10T03:13:26.685+0000] {etl_pipeline.py:87} WARNING - Found 100 invalid records that will not be sent to Kafka
[2025-04-10T03:13:26.690+0000] {etl_pipeline.py:91} INFO - Data validation completed. 0 records ready for loading.
[2025-04-10T03:13:26.690+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-04-10T03:13:26.690+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-10T03:13:26.693+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=realtime_user_streaming_pipeline, task_id=data_validation, run_id=manual__2025-04-10T03:13:23.288254+00:00, execution_date=20250410T031323, start_date=20250410T031326, end_date=20250410T031326
[2025-04-10T03:13:26.726+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-04-10T03:13:26.735+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-04-10T03:13:26.736+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
